TABLE_ (USERS)
SERIAL_ (USER_ID) PRIMARY_KEY
STRING_ (NAME, 30)
DATE_ (DATE_ADDED) SQLDEFAULT(CURRENT_DATE)
END_TABLE

TABLE_ (QUALITIES)
SERIAL_ (QUALITY_ID) PRIMARY_KEY
TIMESTAMP_ (MODIFIED) SQLDEFAULT(CURRENT_TIMESTAMP)
INT_ (QUALITY)
STRING_ (MEMBER, 255)
INT64 (USER_ID) REFERENCES(USERS.USER_ID)
END_TABLE

